PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
baseURL = "http://jssoriao.dev/"
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = true
contentDir = "content"
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
paginate = 10
publishDir = "public"
theme = "github.com/rhazdon/hugo-theme-hello-friend-ng"
title = "John Stephen Soriao"
[author]
name = "John Stephen Soriao"
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 2
[[menu.main]]
identifier = "posts"
name = "Post"
url = "post/"
weight = 1
[[module.imports]]
path = "github.com/rhazdon/hugo-theme-hello-friend-ng"
[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"
description = "Backend Developer and DevOps Engineer"
disableReadOtherPosts = false
enableThemeToggle = true
homeSubtitle = "Backend Developer/DevOps Engineer"
images = [""]
keywords = "backend, web development, devops"
[params.footer]
author = true
bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>"]
copyright = true
topText = []
trademark = true
[params.logo]
logoCursorColor = "#06f1f1"
logoHomeLink = "/"
logoMark = ">"
logoText = "JS"
[[params.social]]
name = "email"
url = "mailto:johnstephensoriao19@gmail.com"
[[params.social]]
name = "github"
url = "https://github.com/jssoriao"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/john-stephen-soriao-450a74163/"
